name: Waka Readme

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_TIME: true
          LANG_COUNT: 5
          SHOW_LINES: false
          COMMIT_MESSAGE: "Update WakaTime stats"
